USE [master]
GO

/****** Object:  Database [NetBankDB]    Script Date: 3/10/2022 6:52:11 PM ******/
CREATE DATABASE [NetBankDB]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NetBankDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NetBankDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NetBankDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NetBankDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NetBankDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NetBankDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [NetBankDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NetBankDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NetBankDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NetBankDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NetBankDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NetBankDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NetBankDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NetBankDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NetBankDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NetBankDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NetBankDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NetBankDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NetBankDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NetBankDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NetBankDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NetBankDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NetBankDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NetBankDB] SET RECOVERY FULL 
GO

ALTER DATABASE [NetBankDB] SET  MULTI_USER 
GO

ALTER DATABASE [NetBankDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NetBankDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NetBankDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NetBankDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NetBankDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NetBankDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [NetBankDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [NetBankDB] SET  READ_WRITE 
GO

