

services:
  
  moneybank-db:
    image: mysql:8.0 
    container_name: moneybank_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: YourStrongPassword!
      MYSQL_DATABASE: moneybankdb 
      MYSQL_USER: moneybankuser 
      MYSQL_PASSWORD: M0n3yB4nkUs3r*01 
    ports:
      - "3307:3306" 
    volumes:
      - moneybank-db-data:/var/lib/mysql 
      
      - ./ScriptsDocker:/docker-entrypoint-initdb.d 


  moneybank-api:
    container_name: moneybank_api_service
    build:
      context: .
      dockerfile: ./MoneyBankService.Api/Dockerfile
    ports:
      - "7000:7000" 
    environment:
      ASPNETCORE_ENVIRONMENT: Development 
      
      ConnectionStrings__CnnStr: "server=moneybank-db;port=3306;database=moneybankdb;user=moneybankuser;password=M0n3yB4nkUs3r*01;Allow User Variables=True"
      ASPNETCORE_URLS: http://+:7000 
    depends_on:
      - moneybank-db 
volumes:
  moneybank-db-data: 