version: '3.8'
services:
  categoryservice:
    image: image_categorys:latest
    networks:
      - trabajoFinal
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3000:80"
      - "3001:443"
    
    depends_on:
      - categoryservicedb
  categoryservicedb:
    image: mysql:8.0.34
    restart: always
    networks:
      - trabajoFinal
    environment:
      MYSQL_DATABASE: 'categoryservicedb'
      MYSQL_USER: 'categoryserviceuser'
      MYSQL_PASSWORD: 'C4t3g0ryS3rv1c3Us3r'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3307:3306"
    volumes:
      - categoryservicedb:/var/lib/mysql
volumes:
  categoryservicedb:
networks:
  trabajoFinal:
    driver: bridge
    name: trabajoFinal