INSERT INTO `arepasdb`.`products` (`Name`, `Description`, `Price`, `Image`) VALUES ('Arepa Sencilla',null,2000,'Arepa-Sencilla.jpg');
INSERT INTO `arepasdb`.`products` (`Name`, `Description`, `Price`, `Image`) VALUES ('Arepa con queso doble crema',null,2500,'Arepa-Rellena-de-Queso.jpg');
INSERT INTO `arepasdb`.`products` (`Name`, `Description`, `Price`, `Image`) VALUES ('Arepa con Jamon y queso doble crema',null,3500,'Arepa-Rellena-Jamon-Queso,jpg');
INSERT INTO `arepasdb`.`products` (`Name`, `Description`, `Price`, `Image`) VALUES ('Arepa con Queso Cuajada',null,3000,'Arepa-Rellena-de-Queso-Cuajada.jpg');
INSERT INTO `arepasdb`.`products` (`Name`, `Description`, `Price`, `Image`) VALUES ('Arepa con Huevos Revueltos',null,4000,'Arepa-Rellena-Huevos-Revueltos.jpg');
INSERT INTO `arepasdb`.`products` (`Name`, `Description`, `Price`, `Image`) VALUES ('Arepa con Salchicha Ranchera',null,5000,'Arepa-Rellena-Salchicha-Ranchera.png');
INSERT INTO `arepasdb`.`products` (`Name`, `Description`, `Price`, `Image`) VALUES ('Arepa con Pollo Desmechado',null,6000,'Arepa-Rellena-Pollo.jpg');
INSERT INTO `arepasdb`.`products` (`Name`, `Description`, `Price`, `Image`) VALUES ('Arepa con Carne Desmechada',null,7000,'Arepa-Rellena-Carne.jpg');
INSERT INTO `arepasdb`.`products` (`Name`, `Description`, `Price`, `Image`) VALUES ('Arepa con Chorizo','Rico y delicioso chorizo santarosano y arepa 100% maiz ',8000,'Arepa-Con-Chorizo.jpg');
INSERT INTO `arepasdb`.`products` (`Name`, `Description`, `Price`, `Image`) VALUES ('Arepa Mixta 2 Ingredientes','Puedes elegir dos carnes Pollo, carne , chorizos y ranchera',8000,'Arepas-Rellenas.jfif');
INSERT INTO `arepasdb`.`products` (`Name`, `Description`, `Price`, `Image`) VALUES ('Arepa Mixta 3 Ingredientes','Puedes elegir tres carnes Pollo, carne chorizos y ranchera',9000,'Arepas-Rellenas.jfif');
INSERT INTO `arepasdb`.`products` (`Name`, `Description`, `Price`, `Image`) VALUES ('Arepa Mixta 4 Ingredientes','Contiene pollo,carne , chorizos y ranchera ',10000,'Arepas-Rellenas.jfif');
INSERT INTO `arepasdb`.`products` (`Name`, `Description`, `Price`, `Image`) VALUES ('Arepa con Todo','Contiene Queso doble crema, pollo, chicharrón, carne, chorizos, pico de gallo',13000,'Arepa-Rellena-Con-Todo.jpg');
