version: '3.8'
services:
  productservice:
    image: santig012/product-service-image:latest
    networks:
      - pricatNetwork
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:80
      - 4001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password*1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/product-certificate.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - productservicedb
  productservicedb:
    image: mysql:8.0.34
    restart: always
    networks:
      - pricatNetwork
    environment:
      MYSQL_DATABASE: 'productservicedb'
      MYSQL_USER: 'productserviceuser'
      MYSQL_PASSWORD: 'Pr0ductS3rv1c3Us3r'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    volumes:
      - productservicedb:/var/lib/mysql
volumes:
  productservicedb:
networks:
  pricatNetwork:
    external: true
