USE [master]
GO


CREATE DATABASE [ReminderDB]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ReminderDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ReminderDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ReminderDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ReminderDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ReminderDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ReminderDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ReminderDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ReminderDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ReminderDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ReminderDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ReminderDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ReminderDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ReminderDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ReminderDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ReminderDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ReminderDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ReminderDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ReminderDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ReminderDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ReminderDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ReminderDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ReminderDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ReminderDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ReminderDB] SET RECOVERY FULL 
GO

ALTER DATABASE [ReminderDB] SET  MULTI_USER 
GO

ALTER DATABASE [ReminderDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ReminderDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ReminderDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ReminderDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ReminderDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ReminderDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ReminderDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ReminderDB] SET  READ_WRITE 
GO

